add authController and add user model
Code-the-Dream-School/hh-team2-back pull request #3
Opened 2024-11-20 22:18 UTC by mojahmed

Before running the project, make sure to install the necessary dependencies

2024-11-20 23:08 UTC, vitaliipp approved these changes
Great job! But please don't commit empty files or code that is commented out. You need two approvals on your PR before it can be merged. I suggest that teammates should merge only their own PRs

2024-11-23 08:24 UTC, tianahR requested changes
Great job ! Before you merge after a mentor's approval, I just requested some minor changes. Thank you

2024-11-23 08:24 UTC, tianahR commented on src/app.js
Just a question : why didn't you just rename the file connect.js to connectToDb.js , instead of creating a new file?

2024-11-23 08:24 UTC, tianahR commented on src/controllers/categoriesController.js
Before merging your code, would you please delete this file to avoid conflict, it's an empty file. Thank you

2024-11-23 08:24 UTC, tianahR commented on src/controllers/commentsController.js
Same here, before merging, would you please delete this file? Thank you

2024-11-23 08:24 UTC, tianahR commented on src/controllers/usersController.js
Great job - adding comments !

2024-11-23 08:24 UTC, tianahR commented on src/routes/categoriesRoute.js
Same here, before merging, would you please delete this file since it's empty and to avoid conflict?

2024-11-23 08:24 UTC, tianahR commented on src/routes/commentsRoute.js
Same here, delete file please

2024-11-23 08:24 UTC, tianahR commented on src/routes/postsRoute.js
Samee here

2024-11-23 08:24 UTC, tianahR commented on src/routes/usersRoute.js
For naming files in the routes folder, since we have "mainRouter", let's use that same type of naming. For example : usersRouter, postRouter .....

2024-11-23 18:07 UTC, butolinka commented
Reviewed, no additions

2024-11-23 18:11 UTC, butolinka reviewed
No additions from me

2024-11-23 18:12 UTC, tianahR approved these changes

2024-11-23 22:03 UTC, merged